services:

  mongodb:
    image: mongo:8.0
    container_name: smart-retail-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - smart-retail-network

  discovery-server:
    image: smart-retail/discovery-server:1.0
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - smart-retail-network

  config-server:
    image: smart-retail/config-server:1.0
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    networks:
      - smart-retail-network

  api-gateway:
    image: smart-retail/api-gateway:1.0
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - config-server
      - discovery-server
    networks:
      - smart-retail-network

  auth-service:
    image: smart-retail/auth-service:1.0
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/auth_db
    depends_on:
      - config-server
      - discovery-server
      - mongodb
    networks:
      - smart-retail-network

  user-service:
    image: smart-retail/user-service:1.0
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/user_db
    depends_on:
      - config-server
      - discovery-server
      - mongodb
    networks:
      - smart-retail-network

  inventory-service:
    image: smart-retail/inventory-service:1.0
    container_name: inventory-service
    ports:
      - "8083:8083"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/inventory_db
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      - config-server
      - discovery-server
      - mongodb
      - zipkin
    networks:
      - smart-retail-network

  order-service:
    image: smart-retail/order-service:1.0
    container_name: order-service
    ports:
      - "8084:8084"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/order_db
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      KAFKA_USERNAME: avnadmin
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
    depends_on:
      - config-server
      - discovery-server
      - mongodb
      - zipkin
    networks:
      - smart-retail-network

  notification-service:
    image: smart-retail/notification-service:1.0
    container_name: notification-service
    ports:
      - "8085:8085"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      KAFKA_USERNAME: avnadmin
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
    depends_on:
      - config-server
      - discovery-server
      - zipkin
    networks:
      - smart-retail-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: smart-retail-zipkin
    ports:
      - "9411:9411"
    networks:
      - smart-retail-network

  prometheus:
    image: prom/prometheus:latest
    container_name: smart-retail-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - smart-retail-network

  grafana:
    image: grafana/grafana:latest
    container_name: smart-retail-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - smart-retail-network

volumes:
  mongo-data:
  grafana-data:

networks:
  smart-retail-network:
    driver: bridge