apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: smart-retail/discovery-server:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
