apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
       containers:
        - name: auth-service
          image: smart-retail/auth-service:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081

          env:
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/