server:
  port: 87618

spring:
  application:
    name: discovery-server

  config:
  import: optional:configserver:http://config-server:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
