server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/inventory_db

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,retries
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans
logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"