server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [corrId=%X{correlationId}] %msg%n"