apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1

  selector:
    matchLabels:
      app: config-server

  template:
    metadata:
      labels:
        app: config-server

    spec:
      containers:
        - name: config-server
          image: smart-retail/config-server:1.0

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8888

          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/